# Generated by Django 5.1.4 on 2025-02-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='client_price',
            field=models.IntegerField(default=0),
        ),
    ]
