# Generated by Django 5.1.4 on 2025-02-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniform',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='uniform',
            name='updated_at',
        ),
    ]
