# Generated by Django 5.1.4 on 2025-03-24 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/uniforms/'),
        ),
        migrations.AddField(
            model_name='uniform',
            name='job_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uniforms', to='users.jobrole'),
            preserve_default=False,
        ),
    ]
