# Generated by Django 5.1.4 on 2025-01-16 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_staffinvitation_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='staff_invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_invitation', to='users.staffinvitation'),
        ),
    ]
