# Generated by Django 5.1.4 on 2025-01-21 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_invitation_job_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitation_code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='job_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_job_role', to='users.jobrole'),
        ),
    ]
