# Generated by Django 5.1.4 on 2025-01-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_invitation_invitation_code_alter_invitation_job_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='code_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
