# Generated by Django 5.1.4 on 2025-01-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_uniform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniform',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
