# Generated by Django 5.1.4 on 2025-01-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_uniform_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='uniform',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
