# Generated by Django 5.1.4 on 2025-01-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_jobrole_name_alter_uniform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='uniform',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
