# Generated by Django 5.1.4 on 2025-01-26 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('staff', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystaff',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
    ]
