# Generated by Django 5.1.4 on 2025-01-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job Vacancy', 'verbose_name_plural': 'Job Vacancy'},
        ),
        migrations.RenameField(
            model_name='jobtemplate',
            old_name='profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='profile',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='job',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.ManyToManyField(blank=True, null=True, related_name='vacancies', to='client.vacancy'),
        ),
    ]
