# Generated by Django 5.1.4 on 2025-01-14 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('users', '0007_alter_jobrole_name_alter_uniform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='save_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default='PUBLISHED', max_length=10),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancy',
            field=models.ManyToManyField(blank=True, related_name='vacancies', to='client.vacancy'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_title',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.jobrole'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='uniform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.uniform'),
        ),
    ]
