# Generated by Django 5.1.4 on 2025-01-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_jobapplication_in_time_jobapplication_out_time_and_more'),
        ('staff', '0004_remove_staff_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffInfitation',
            new_name='StaffInvitation',
        ),
    ]
