# Generated by Django 5.1.4 on 2025-01-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_job_save_template_job_status_vacancy_salary_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='staff.staff'),
        ),
    ]
