# Generated by Django 5.1.4 on 2025-01-26 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_mystaff_staff'),
        ('staff', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystaff',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
            preserve_default=False,
        ),
    ]
