# Generated by Django 5.1.4 on 2025-02-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientreview_delete_staffreview'),
        ('staff', '0004_bankdetails_country_bankdetails_post_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientReview',
            new_name='CompanyReview',
        ),
    ]
