# Generated by Django 5.1.4 on 2025-01-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_job_save_template_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vacancy',
            field=models.ManyToManyField(blank=True, related_name='vacancies', to='client.vacancy'),
        ),
    ]
