# Generated by Django 5.1.4 on 2025-02-22 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_rename_clientreview_companyreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreview',
            name='client',
        ),
        migrations.RemoveField(
            model_name='companyreview',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='companyreview',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.jobapplication'),
            preserve_default=False,
        ),
    ]
