# Generated by Django 5.1.4 on 2025-02-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtemplate',
            options={'verbose_name': 'Job Template', 'verbose_name_plural': 'Job Templates'},
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
