# Generated by Django 5.1.4 on 2025-01-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_mystaff_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='one_day_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='open_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
