# Generated by Django 5.1.4 on 2025-01-08 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_job_created_at_job_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_templates', to='client.jobtemplate'),
        ),
    ]
