# Generated by Django 5.1.4 on 2025-02-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vacancy',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='client.vacancy'),
        ),
    ]
