# Generated by Django 5.1.4 on 2025-02-17 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='client',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='client.companyprofile'),
            preserve_default=False,
        ),
    ]
