# Generated by Django 5.1.4 on 2025-03-12 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_initial'),
        ('staff', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritestaff',
            name='staff',
        ),
        migrations.AddField(
            model_name='favouritestaff',
            name='staff',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favourites_staff', to='staff.staff'),
            preserve_default=False,
        ),
    ]
