# Generated by Django 5.1.4 on 2025-03-14 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_favouritestaff_staff_favouritestaff_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritestaff',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.companyprofile'),
        ),
    ]
