# Generated by Django 5.1.4 on 2025-02-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_job_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('UPCOMMING', 'UPCOMMING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('EXPIRED', 'EXPIRED')], default='UPCOMMING', max_length=10),
        ),
    ]
