# Generated by Django 5.1.4 on 2025-02-22 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_companyreview_client_and_more'),
        ('staff', '0004_bankdetails_country_bankdetails_post_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyreview',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Company Reviews'},
        ),
        migrations.RemoveField(
            model_name='companyreview',
            name='application',
        ),
        migrations.AddField(
            model_name='companyreview',
            name='review_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='review_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.companyprofile'),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
