# Generated by Django 5.1.4 on 2025-01-13 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_job_vacancy'),
        ('users', '0005_alter_uniform_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_title',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.jobrole'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='uniform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.uniform'),
        ),
    ]
