# Generated by Django 5.1.4 on 2025-02-17 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_vacancy_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='client',
        ),
    ]
