# Generated by Django 5.1.4 on 2025-03-24 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_favouritestaff_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobreport',
            name='tax',
        ),
        migrations.AddField(
            model_name='companyreview',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.jobapplication'),
        ),
    ]
