# Generated by Django 5.1.4 on 2025-02-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_jobapplication_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('upcomming', 'UPCOMMING'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED'), ('expired', 'EXPIRED')], default='pending', max_length=10),
        ),
    ]
