# Generated by Django 5.1.4 on 2025-01-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_jobapplication_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job',
            new_name='vacancy',
        ),
    ]
