# Generated by Django 5.1.4 on 2025-01-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_companyreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreview',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
