# Generated by Django 5.1.4 on 2025-04-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_remove_jobreport_tax_companyreview_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtemplate',
            options={'verbose_name': 'Job Template', 'verbose_name_plural': 'Job-Templates'},
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
