# Generated by Django 5.1.4 on 2025-02-03 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_jobapplication_job_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='status',
            new_name='is_approve',
        ),
    ]
