# Generated by Django 5.1.4 on 2025-02-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_jobapplication_job_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='status',
            new_name='is_approved',
        ),
        migrations.AddField(
            model_name='checkin',
            name='distance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
