# Generated by Django 5.1.4 on 2025-01-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_companyreview_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyReview',
        ),
    ]
