# Generated by Django 5.1.4 on 2025-02-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_jobreport_tips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritestaff',
            name='updated_at',
        ),
    ]
