# Generated by Django 5.1.4 on 2025-01-31 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_companyprofile_user'),
        ('staff', '0004_alter_staff_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='user',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='client',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='client.companyprofile'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['open_date', 'close_date', 'start_time', 'end_time'], name='client_vaca_open_da_48c6cf_idx'),
        ),
    ]
