# Generated by Django 5.1.4 on 2025-01-20 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_delete_companyreview'),
        ('users', '0005_alter_invitation_staff_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('job_type', models.CharField(choices=[('full time', 'full time'), ('part time', 'part time'), ('contract', 'contract')], default='full time', max_length=20)),
                ('number_of_staff', models.IntegerField(default=1)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('website_url', models.URLField(blank=True)),
                ('contact_percentage', models.IntegerField(default=0)),
                ('login_email', models.EmailField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.companyprofile')),
                ('skills', models.ManyToManyField(blank=True, related_name='permanent_skills', to='users.skill')),
            ],
            options={
                'verbose_name': 'Permanent Job',
                'verbose_name_plural': 'Permanent Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
