# Generated by Django 5.1.4 on 2025-04-16 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_jobtemplate_options_jobtemplate_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='checkin',
            name='application',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='client.jobapplication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkin',
            name='distance',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='is_approved',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
