# Generated by Django 5.1.4 on 2025-02-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_rename_status_jobapplication_is_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
