# Generated by Django 5.1.4 on 2025-02-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_rename_status_checkin_is_approved_checkin_distance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='one_day_job',
            new_name='checkin_status',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='checkout_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='shift_job',
            field=models.BooleanField(default=False),
        ),
    ]
