# Generated by Django 5.1.4 on 2025-02-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_vacancy_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='job_status',
            field=models.CharField(choices=[('active', 'Active'), ('progress', 'InProgress'), ('draft', 'Draft'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], default='active', max_length=255),
        ),
    ]
