# Generated by Django 5.1.4 on 2025-01-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_permanentjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanentjobs',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permanentjobs',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
