# Generated by Django 5.1.4 on 2025-02-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_rename_one_day_job_vacancy_checkin_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='checkin_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='checout_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED'), ('expired', 'EXPIRED')], default='pending', max_length=10),
        ),
    ]
