# Generated by Django 5.1.4 on 2025-01-31 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_job_description'),
        ('staff', '0004_alter_staff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.companyprofile')),
                ('staff', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'verbose_name_plural': 'Favourite Staff',
                'ordering': ['-created_at'],
            },
        ),
    ]
