# Generated by Django 5.1.4 on 2025-04-16 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_remove_checkin_staff_remove_checkin_vacancy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='status',
            new_name='is_approved',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='checkout',
            name='application',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='client.jobapplication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='distance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
