# Generated by Django 5.1.4 on 2025-01-21 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_permanentjobs_is_paid_and_more'),
        ('staff', '0005_staff_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_status',
            field=models.CharField(choices=[('UPCOMMING', 'UPCOMMING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('EXPIRED', 'EXPIRED')], default='UPCOMMING', max_length=10),
        ),
        migrations.CreateModel(
            name='JobAdsJoiningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('joininig_date', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.permanentjobs')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
    ]
