# Generated by Django 5.1.4 on 2025-01-31 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_favouritestaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritestaff',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.companyprofile'),
        ),
    ]
