# Generated by Django 5.1.4 on 2025-02-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_jobapplication_checkin_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='checkin_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='checkout_approve',
            field=models.BooleanField(default=False),
        ),
    ]
