# Generated by Django 5.1.4 on 2025-04-17 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_rename_status_checkout_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobreport',
            name='job_application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.jobapplication'),
        ),
    ]
