# Generated by Django 5.1.4 on 2025-01-31 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_favouritestaff_company'),
        ('staff', '0005_staff_role_delete_staffrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritestaff',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
    ]
