# Generated by Django 5.1.4 on 2025-02-06 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_companyprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtemplate',
            name='user',
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.companyprofile'),
            preserve_default=False,
        ),
    ]
