# Generated by Django 5.1.4 on 2025-01-31 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_favouritestaff_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritestaff',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.companyprofile'),
        ),
    ]
