# Generated by Django 5.1.4 on 2025-04-19 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_jobreport_job_application'),
        ('staff', '0003_alter_bankdetails_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED'), ('expired', 'EXPIRED'), ('late', 'LATE'), ('completed', 'COMPLETED')], default='pending', max_length=10),
        ),
    ]
