# Generated by Django 5.1.4 on 2025-02-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_rename_checout_location_jobapplication_checkout_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='delay',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
