# Generated by Django 5.1.4 on 2025-01-31 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_alter_favouritestaff_company'),
        ('staff', '0005_staff_role_delete_staffrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritestaff',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.companyprofile'),
        ),
        migrations.RemoveField(
            model_name='favouritestaff',
            name='staff',
        ),
        migrations.AddField(
            model_name='favouritestaff',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='favourites_staff', to='staff.staff'),
        ),
    ]
