# Generated by Django 5.1.4 on 2025-04-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_alter_jobapplication_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
