# Generated by Django 5.1.4 on 2025-02-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_jobapplication_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='delay',
            field=models.DurationField(blank=True, default=0, null=True),
        ),
    ]
