# Generated by Django 5.1.4 on 2025-01-31 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_favouritestaff_company_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermanentJobs',
            new_name='JobAds',
        ),
    ]
