# Generated by Django 5.1.4 on 2025-02-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_alter_jobapplication_delay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='delay',
            new_name='total_working_hours',
        ),
    ]
