# Generated by Django 5.1.4 on 2025-02-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_rename_delay_jobapplication_total_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED'), ('expired', 'EXPIRED'), ('completed', 'COMPLETED')], default='pending', max_length=10),
        ),
    ]
