# Generated by Django 5.1.4 on 2025-02-13 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_alter_jobapplication_job_status'),
        ('staff', '0014_delete_staffreview'),
        ('users', '0003_remove_skill_created_at_remove_skill_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hour', models.IntegerField(blank=True, null=True)),
                ('extra_hour', models.IntegerField(blank=True, null=True)),
                ('regular_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overtime_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(decimal_places=2, default=25, max_digits=10, null=True)),
                ('total_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.jobapplication')),
            ],
            options={
                'verbose_name_plural': 'Job Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.companyprofile')),
                ('job_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.jobrole')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'verbose_name_plural': 'Staff Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
