# Generated by Django 5.1.4 on 2025-02-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_remove_staffreview_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='total_working_hours',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
