# Generated by Django 5.1.4 on 2025-01-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='staff_roles', to='staff.staffrole'),
        ),
    ]
