# Generated by Django 5.1.4 on 2025-02-09 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_initial'),
        ('users', '0003_remove_skill_created_at_remove_skill_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='nid_number',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.jobrole'),
        ),
    ]
