# Generated by Django 5.1.4 on 2025-02-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_letme_staff',
            field=models.BooleanField(default=True),
        ),
    ]
