# Generated by Django 5.1.4 on 2025-04-29 09:13

import staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_bankdetails_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=staff.models.CustomS3Storage(), upload_to='staff/avatar/'),
        ),
    ]
