# Generated by Django 5.1.4 on 2025-02-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_country_staff_gender_staff_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='swift_code',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
