# Generated by Django 5.1.4 on 2025-02-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_about_staff_age_staff_nid_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='video_resume',
            new_name='video_cv',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='exp_year',
        ),
        migrations.DeleteModel(
            name='StaffRole',
        ),
    ]
