# Generated by Django 5.1.4 on 2025-02-09 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_rename_video_resume_staff_video_cv_and_more'),
        ('users', '0003_remove_skill_created_at_remove_skill_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'verbose_name_plural': 'Bank Details',
                'ordering': ['staff'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('present', models.BooleanField(default=False)),
                ('job_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.jobrole')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'verbose_name_plural': 'Experience',
                'ordering': ['-start_date'],
                'unique_together': {('staff', 'job_role')},
            },
        ),
    ]
