# Generated by Django 5.1.4 on 2025-01-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staff_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='staff_roles', to='users.jobrole'),
        ),
        migrations.DeleteModel(
            name='StaffRole',
        ),
    ]
