# Generated by Django 5.1.4 on 2025-01-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_staff_role'),
        ('users', '0005_alter_invitation_staff_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='staff_skill', to='users.skill'),
        ),
    ]
