# Generated by Django 5.1.4 on 2025-02-24 08:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_companyreview_options_and_more'),
        ('staff', '0004_bankdetails_country_bankdetails_post_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('vacancy', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.vacancy')),
            ],
            options={
                'verbose_name_plural': 'Staff Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
