# Generated by Django 5.1.4 on 2025-02-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_bankdetails_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetails',
            old_name='holder_name',
            new_name='card_holder_name',
        ),
    ]
