# Generated by Django 5.1.4 on 2025-02-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_rename_holder_name_bankdetails_card_holder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
