# Generated by Django 5.1.4 on 2025-02-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_companyreview_options_and_more'),
        ('staff', '0007_alter_staffreview_review_by'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='staffreview',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_check'),
        ),
    ]
