# Generated by Django 5.1.4 on 2025-02-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_experience_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
