# Generated by Django 5.1.4 on 2025-02-09 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_experience_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='staff.staff'),
        ),
    ]
