# Generated by Django 5.1.4 on 2025-02-09 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_experience_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='staff.staff'),
        ),
    ]
