# Generated by Django 5.1.4 on 2025-02-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_alter_experience_staff'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='staff',
            name='experience',
            field=models.ManyToManyField(blank=True, related_name='staff_experience', to='staff.experience'),
        ),
        migrations.RemoveField(
            model_name='experience',
            name='staff',
        ),
    ]
