# Generated by Django 5.1.4 on 2025-02-13 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_alter_jobapplication_job_status'),
        ('staff', '0012_experience_user'),
        ('users', '0003_remove_skill_created_at_remove_skill_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.companyprofile')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobrole')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'verbose_name_plural': 'Staff Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
