# Generated by Django 5.1.4 on 2025-02-13 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_staffreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffReview',
        ),
    ]
