# Generated by Django 5.1.4 on 2025-02-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('checkin_location', models.CharField(blank=True, max_length=255, null=True)),
                ('checkout_location', models.CharField(blank=True, max_length=255, null=True)),
                ('checkin_status', models.BooleanField(default=False)),
                ('checkout_status', models.BooleanField(default=False)),
                ('shift_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('post_job', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Shifts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shifting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Shifts',
                'ordering': ['-created_at'],
            },
        ),
    ]
