# Generated by Django 5.1.4 on 2025-02-08 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('shifting', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyshift',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
        migrations.AddField(
            model_name='shifting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.companyprofile'),
        ),
        migrations.AddField(
            model_name='shifting',
            name='shift_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.mystaff'),
        ),
        migrations.AddField(
            model_name='dailyshift',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='shifting.shifting'),
        ),
        migrations.AlterUniqueTogether(
            name='shifting',
            unique_together={('company', 'shift_for')},
        ),
    ]
