# Generated by Django 5.1.4 on 2025-01-26 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifting',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shifting.dailyshift'),
        ),
    ]
