# Generated by Django 5.1.4 on 2025-01-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifting', '0002_alter_shifting_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifting',
            name='shift',
        ),
        migrations.AddField(
            model_name='shifting',
            name='shift',
            field=models.ManyToManyField(blank=True, related_name='daily_shifts', to='shifting.dailyshift'),
        ),
    ]
