# Generated by Django 5.1.4 on 2025-01-26 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_mystaff_staff'),
        ('shifting', '0003_remove_shifting_shift_shifting_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifting',
            name='shift',
        ),
        migrations.AlterField(
            model_name='shifting',
            name='shift_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.mystaff'),
        ),
        migrations.AddField(
            model_name='shifting',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shifting.dailyshift'),
        ),
    ]
