# Generated by Django 5.1.4 on 2025-01-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifting', '0005_remove_shifting_shift_shifting_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyshift',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
