# Generated by Django 5.1.4 on 2025-01-26 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifting', '0006_dailyshift_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifting',
            name='shift',
        ),
        migrations.AddField(
            model_name='dailyshift',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='shifting.shifting'),
        ),
    ]
