# Generated by Django 5.1.4 on 2025-01-27 06:20

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifting', '0007_remove_shifting_shift_dailyshift_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyshift',
            name='checkin_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyshift',
            name='checkoin_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dailyshift',
            name='checkout_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dailyshift',
            name='checkout_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 27, 6, 20, 43, 366529, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyshift',
            name='shift_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
