# Generated by Django 5.1.4 on 2025-01-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifting', '0008_dailyshift_checkin_time_dailyshift_checkoin_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyshift',
            name='checkin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='checkoin_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='checkout_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
