# Generated by Django 5.1.4 on 2025-01-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifting', '0009_alter_dailyshift_checkin_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyshift',
            name='checkin_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyshift',
            name='checkout_status',
            field=models.BooleanField(default=False),
        ),
    ]
