# Generated by Django 5.1.4 on 2025-01-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifting', '0010_dailyshift_checkin_status_dailyshift_checkout_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyshift',
            old_name='checkoin_location',
            new_name='checkin_location',
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='shift_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
