# Generated by Django 5.1.4 on 2025-01-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifting', '0011_rename_checkoin_location_dailyshift_checkin_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyshift',
            name='post_job',
            field=models.BooleanField(default=False),
        ),
    ]
