# Generated by Django 5.1.4 on 2025-01-31 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouriteStaff',
        ),
    ]
