# Generated by Django 5.1.4 on 2025-02-13 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffReview',
        ),
    ]
