# Generated by Django 5.1.4 on 2025-01-19 10:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_delete_companyreview'),
        ('dashboard', '0003_companyreview'),
        ('staff', '0004_remove_staff_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.companyprofile')),
                ('staff', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('vacancy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.vacancy')),
            ],
        ),
    ]
